name: '{project_name}'
version: '1.0.1'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: '{project_name}'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Define model configurations
models:
  sbdk_project:
    # Staging models
    staging:
      +materialized: view
      +docs:
        node_color: "lightblue"
    
    # Intermediate models  
    intermediate:
      +materialized: view
      +docs:
        node_color: "orange"
    
    # Mart models (final output)
    marts:
      +materialized: table
      +docs:
        node_color: "green"

# Test configurations
tests:
  +store_failures: true

# Seed configurations
seeds:
  +quote_columns: false

# Documentation
vars:
  # Define any project variables here
  start_date: '2022-01-01'
  end_date: '2024-12-31'

# Freshness tests
sources:
  sbdk_project:
    +database: main
    +schema: main